name: dart_node_core
description: Core JS interop utilities for dart_node packages
version: 0.9.0-beta
repository: https://github.com/MelbourneDeveloper/dart_node
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  austerity: 1.3.0
  nadz: 0.0.7-beta
  node_preamble: ^2.0.2

dev_dependencies:
  dart_node_coverage:
    path: ../dart_node_coverage
  test: ^1.24.0
