name: dart_node_core
description: Core JS interop utilities for dart_node packages
version: 0.1.0-beta
repository: https://github.com/MelbourneDeveloper/dart_node

environment:
  sdk: ^3.10.0

dependencies:
  austerity: ^1.3.0
  nadz: ^0.0.7-beta
  node_preamble: ^2.0.2
