name: dart_node_better_sqlite3
description: Typed Dart bindings for better-sqlite3 npm package
version: 0.9.0-beta
repository: https://github.com/MelbourneDeveloper/dart_node
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  austerity: 1.3.0
  dart_node_core:
    path: ../dart_node_core
  nadz: 0.0.7-beta

dev_dependencies:
  dart_node_coverage:
    path: ../dart_node_coverage
  test: ^1.24.0
