name: dart_node_react_native
description: React Native bindings for Dart
version: 0.9.0-beta
repository: https://github.com/MelbourneDeveloper/dart_node
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  austerity: 1.3.0
  dart_node_core:
    path: ../dart_node_core
  dart_node_react:
    path: ../dart_node_react
  nadz: 0.0.7-beta

dev_dependencies:
  dart_node_coverage:
    path: ../dart_node_coverage
  lints: ^5.0.0
  test: ^1.24.0
