name: dart_node_react_native
description: React Native bindings for Dart
version: 0.1.0-beta
repository: https://github.com/MelbourneDeveloper/dart_node

environment:
  sdk: ^3.10.0

dependencies:
  austerity: ^1.3.0
  dart_node_core: ^0.1.0-beta
  dart_node_react: ^0.1.0-beta

dev_dependencies:
  lints: ^5.0.0
