name: reflux
description: Predictable state container for Dart apps - inspired by Redux patterns
version: 0.9.0-beta
repository: https://github.com/MelbourneDeveloper/dart_node
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  austerity: 1.3.0
  dart_logging:
    path: ../dart_logging
  nadz: 0.0.7-beta

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
