name: mobile
description: React Native mobile app in Dart
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  austerity: 1.3.0
  dart_node_react:
    path: ../../packages/dart_node_react
  dart_node_react_native:
    path: ../../packages/dart_node_react_native
  nadz: 0.0.7-beta
  shared:
    path: ../shared

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
