name: dart_node_express
description: Express.js bindings for Dart
version: 0.2.0-beta
repository: https://github.com/MelbourneDeveloper/dart_node

environment:
  sdk: ^3.10.0

dependencies:
  austerity: ^1.3.0
  dart_node_core: ^0.2.0-beta
