name: dart_node_coverage
description: Coverage collection for Dart tests running on Node.js (dart2js)
version: 0.9.0-beta
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^9.0.0
  nadz: 0.0.7-beta
  path: ^1.9.1

dev_dependencies:
  austerity: 1.3.0
  node_preamble: ^2.0.2
  test: ^1.28.0

executables:
  coverage:
