name: Publish Tier 3

on:
  workflow_run:
    workflows: ["Publish Tier 2"]
    types: [completed]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_publish-packages.yml
    with:
      tier: 3
      packages: "dart_node_react dart_node_react_native"
      environment: pub.dev-tier3
    secrets: inherit
